spring:
    datasource:
        url: jdbc:mysql://localhost:3306/poretti?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    http:
      multipart: max-file-size=128KB
