package com.bdzjn.poretti.model.enumeration;


public enum Permission {
    CREATE_ADVERTISEMENT,
    EDIT_ADVERTISEMENT,
    CREATE_REVIEW,
    DELETE_REVIEW,
    REPORT_ADVERTISEMENT,
    CREATE_COMPANY_ADVERTISEMENT,
    EDIT_COMPANY_ADVERTISEMENT,
    APPROVE_COMPANY_USER,
    REMOVE_USER_FROM_COMPANY,
    EDIT_COMPANY,
    CHANGE_ADVERTISEMENT_STATUS, // for verify, invalidate, approve ...
    CREATE_COMPANY,
    CREATE_VERIFIER,
    CREATE_SYSTEM_ADMIN,
    BAN_USER
}
