package com.bdzjn.poretti.model.enumeration;


public enum Permission {
    CREATE_ADVERTISEMENT,
    EDIT_ADVERTISEMENT,
    DELETE_ADVERTISEMENT,
    CREATE_REVIEW,
    DELETE_REVIEW,
    CREATE_ADVERTISEMENT_REPORT,
    APPROVE_COMPANY_USER,
    REMOVE_USER_FROM_COMPANY,
    EDIT_COMPANY,
    CHANGE_ADVERTISEMENT_STATUS, // for verify, invalidate, approve ...
    CREATE_COMPANY,
    CREATE_VERIFIER,
    CREATE_SYSTEM_ADMIN,
    JOIN_COMPANY,
    LEAVE_COMPANY,
    BAN_USER
}
